# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip2',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip2'),
        ),
    ]
