# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='owner',
        ),
    ]
